### ISSUE TITLE
Resource leak in Download List

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#161]
08-08 14:46:42.730 7713-7722/org.mozilla.zerda.debug.tyu E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                       java.lang.Throwable: Explicit termination method 'close' not called
                                                                           at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                           at android.content.ContentResolver$CursorWrapperInner.<init>(ContentResolver.java:2627)
                                                                           at android.content.ContentResolver.query(ContentResolver.java:558)
                                                                           at android.content.ContentResolver.query(ContentResolver.java:474)
                                                                           at android.app.DownloadManager$Query.runQuery(DownloadManager.java:947)
                                                                           at android.app.DownloadManager.query(DownloadManager.java:1055)
                                                                           at org.mozilla.focus.greenDAO.DownloadInfo.<init>(DownloadInfo.java:28)
                                                                           at org.mozilla.focus.greenDAO.DBService.getAllDownloadInfo(DBService.java:57)
                                                                           at org.mozilla.focus.widget.DownloadListAdapter.fetchEntity(DownloadListAdapter.java:36)
                                                                           at org.mozilla.focus.widget.DownloadListAdapter.<init>(DownloadListAdapter.java:31)
                                                                           at org.mozilla.focus.widget.DownloadDialogShowListener.<init>(DownloadDialogShowListener.java:30)
                                                                           at org.mozilla.focus.activity.MainActivity.setUpHistoryAndDownload(MainActivity.java:196)
                                                                           at org.mozilla.focus.activity.MainActivity.initViews(MainActivity.java:182)
                                                                           at org.mozilla.focus.activity.MainActivity.onCreate(MainActivity.java:54)
                                                                           at android.app.Activity.performCreate(Activity.java:6682)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

This would make Zerda unable to crash on every launch with Strict mode.

current head is 27da89d

**Comment by mTwTm** [comment]
What I was playing with:

Trying to download and cancel a file for 15 times to see if items can be scrolled correctly

**Comment by mTwTm** [comment]
P.S If you have encountered the same problem, clear data would do the trick.

**Comment by mTwTm** [comment]
@WeiWW I guess you can help with this? ;)

**Comment by chianger** [comment]
likely resolved. need to verify.

**Comment by idiotmax** [comment]
Closed by #207

**Comment by Conjuror** [comment]
This is in debug mode only and barely be able to verify by QA. Closed it for now.
