### ISSUE TITLE
Crash after leaving Screenshot Viewer

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#466]

**Comment by mTwTm** [comment]
setTargetFragment() is discouraged
Ref: https://stackoverflow.com/questions/29714476/fragment-no-longer-exists-for-key-androidtarget-state, https://issuetracker.google.com/issues/36969568

**Comment by mTwTm** [comment]
Process: org.mozilla.zerda.debug.tyu, PID: 18287
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.zerda.debug.tyu/org.mozilla.focus.activity.MainActivity}: java.lang.IllegalStateException: Fragment no longer exists for key android:target_state: index 1
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                              Caused by: java.lang.IllegalStateException: Fragment no longer exists for key android:target_state: index 1
                                                                                 at android.support.v4.app.FragmentManagerImpl.getFragment(FragmentManager.java:874)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1210)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                 at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2893)
                                                                                 at android.support.v4.app.Fragment.restoreChildFragmentState(Fragment.java:1294)
                                                                                 at android.support.v4.app.Fragment.onCreate(Fragment.java:1265)
                                                                                 at android.support.v4.app.DialogFragment.onCreate(DialogFragment.java:291)
                                                                                 at android.support.v4.app.Fragment.performCreate(Fragment.java:2180)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1244)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                 at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2893)
                                                                                 at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:190)
                                                                                 at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:353)
                                                                                 at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
                                                                                 at org.mozilla.focus.locale.LocaleAwareAppCompatActivity.onCreate(LocaleAwareAppCompatActivity.java:39)
                                                                                 at org.mozilla.focus.activity.MainActivity.onCreate(MainActivity.java:81)
                                                                                 at android.app.Activity.performCreate(Activity.java:6682)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:154) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by mTwTm** [comment]
Duplicate to #258
