### ISSUE TITLE
Crash when entering preference from bottomsheet

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#66]
STR:

1. Open bottom sheet
2. Click preference
3. hit back
4. Crash

**Comment by mTwTm** [comment]
@walkingice you might be interested

**Comment by mTwTm** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void org.mozilla.focus.home.TopSitesContract$Presenter.populateSites()' on a null object reference
                                                     at org.mozilla.focus.home.HomeFragment.onViewCreated(HomeFragment.java:55)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                     at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2900)
                                                     at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
                                                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
                                                     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                                                     at android.app.Activity.performStart(Activity.java:6699)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2629)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by Conjuror** [comment]
Not sure it's still valid. Unable to reproduce from my side. suggest to close it if we cannot reproduce. Any comments? @mTwTm

**Comment by mTwTm** [comment]
It's an issue that should have closed long ago via #80

**Comment by Conjuror** [comment]
Unable to reproduce. Marked as verified
