### ISSUE TITLE
[Smoke Test] Crashes when opening screenshot viewer after visiting any page 

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#937]
STR:
1. Visit facebook.com
2. Take screenshot
3. Tap on menu
4. Tap on My shots
5. Tap on the screenshot just taken

Build: 1238
DuT: Oppo, mito

**Comment by Conjuror** [comment]
Per Kuan-ting's and Eric's update, no such issue in build 1158. (Beta 2 Candidate)

**Comment by Conjuror** [comment]
dup #936 and #935

**Comment by walkingice** [comment]
might relative to this log

```
09-26 10:51:34.672 24297 24307 E StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
09-26 10:51:34.672 24297 24307 E StrictMode: java.lang.Throwable: Explicit termination method 'close' not called
09-26 10:51:34.672 24297 24307 E StrictMode:    at dalvik.system.CloseGuard.open(CloseGuard.java:180)
09-26 10:51:34.672 24297 24307 E StrictMode:    at java.io.FileInputStream.<init>(FileInputStream.java:78)
09-26 10:51:34.672 24297 24307 E StrictMode:    at java.io.FileInputStream.<init>(FileInputStream.java:103)
09-26 10:51:34.672 24297 24307 E StrictMode:    at android.media.ExifInterface.loadAttributes(ExifInterface.java:1338)
09-26 10:51:34.672 24297 24307 E StrictMode:    at android.media.ExifInterface.<init>(ExifInterface.java:1057)
09-26 10:51:34.672 24297 24307 E StrictMode:    at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.getExifOrientation(SubsamplingScaleImageView.java:1807)
09-26 10:51:34.672 24297 24307 E StrictMode:    at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.access$5200(SubsamplingScaleImageView.java:81)
09-26 10:51:34.672 24297 24307 E StrictMode:    at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1691$
09-26 10:51:34.672 24297 24307 E StrictMode:    at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1664$
09-26 10:51:34.672 24297 24307 E StrictMode:    at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-26 10:51:34.672 24297 24307 E StrictMode:    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-26 10:51:34.672 24297 24307 E StrictMode:    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-26 10:51:34.672 24297 24307 E StrictMode:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-26 10:51:34.672 24297 24307 E StrictMode:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-26 10:51:34.672 24297 24307 E StrictMode:    at java.lang.Thread.run(Thread.java:818)
09-26 10:51:34.672 24297 24307 W System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
```

**Comment by mTwTm** [comment]
Duplicate to #714

**Comment by dakaizou** [comment]
verified as dup
